/**
 * Constants shared between the CMS (apps/cms) and the web frontend (apps/web).
 */

/** Collection slugs exposed over the REST API and consumed by the frontend. */
export const COLLECTION_SLUGS = {
  pages: 'pages',
  posts: 'posts',
  media: 'media',
  categories: 'categories',
  search: 'search',
  redirects: 'redirects',
  forms: 'forms',
  formSubmissions: 'form-submissions',
} as const

/** Image rendition names generated by the Media collection (sharp-era uploads). */
export const IMAGE_SIZES = [
  'thumbnail',
  'square',
  'small',
  'medium',
  'large',
  'xlarge',
  'og',
] as const

/** Name of the HttpOnly cookie that enables draft-content fetching on the web app. */
export const DRAFT_COOKIE = 'athena-draft'

/** Cache-tag names used for KV version stamps in the web app's cache layer. */
export const CACHE_TAGS = {
  pages: 'pages',
  posts: 'posts',
  header: 'global_header',
  footer: 'global_footer',
  redirects: 'redirects',
  sitemap: 'sitemap',
} as const

export type CacheTag = (typeof CACHE_TAGS)[keyof typeof CACHE_TAGS]
